### ISSUE TITLE
Does this still work on the newest January update?

### ISSUE THREAD

**Issue by Cy1der** [wavezcs/SonicPadObico#2]
title

**Comment by awid777** [comment]
I am running the latest update...sadly I am having no luck obtaining root.

**Comment by Cy1der** [comment]
that's unfortunate...

**Comment by Perkaholic999** [comment]
I still have root and was able to link my printer but I get an error in obico https://imgur.com/a/S6vridq

**Comment by broderickgoncalves** [comment]
This work ?

**Comment by wavezcs** [comment]
> 

Yes, still works for me
