### ISSUE TITLE
now using obico-start.sh but it doesn't auto start

### ISSUE THREAD

**Issue by LeBrunton** [wavezcs/SonicPadObico#5]
Thanks for sharing the text for the obico-start.sh, however having added the cron entry it still doesn't start at boot.

is there anything you can suggest i try?

**Comment by fran6p** [comment]
It can't work with crontab as @reboot doesn't exist in Busybox of OpenWRT.
If you want that Obico start after Moonraker, you'll have to insert the command to obico-start.sh in the file /etc/rc.local before «exit 0».
```
…
sleep 30 && /usr/share/moonraker-obico/obico-start.sh
exit 0
```

**Comment by LeBrunton** [comment]
ok just tried that, and still no luck - it doesn't auto start :(

**Comment by fran6p** [comment]
Does it works when you send manually the command ?
Does the obico-start.sh is executable ? If not, try a chmod +x /usr/share/moonraker-obico/obico-start.sh.
Have yo deleted the cron job ? crontab -r will do.
Here, on my printers it works with the script at startup with rc.local.

**Comment by LeBrunton** [comment]
If I manually run the script obico-start.sh it works. If I manually enter the sleep 30 && /usr/share/moonraker-obico/obico-start.sh I get:

/usr/share/moonraker-obico/env/bin/python3: Error while finding module specification for 'moonraker_obico.app' (ModuleNotFoundError: No module named 'moonraker_obico')

**Comment by fran6p** [comment]
My script obico-start.sh is a little different : 
`#!/bin/sh
PYTHONPATH=/usr/share/moonraker-obico
PROG="$PYTHONPATH/env/bin/python3"

cd $PYTHONPATH
source env/bin/activate
$PROG -m moonraker_obico.app -c $PYTHONPATH/moonraker-obico.cfg`

My rc.local : 
`# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.

# hpout playback
#amixer -D hw:audiocodec cset name='Headphone Switch' 1
#amixer -D hw:audiocodec cset name='Headphone Volume' 3
#amixer -D hw:audiocodec cset name='HpSpeaker Switch' 1

# lineout playback
#amixer -D hw:audiocodec cset name='LINEOUT Output Select' 'DAC_DIFFER'
#amixer -D hw:audiocodec cset name='LINEOUT Switch' 1
#amixer -D hw:audiocodec cset name='LINEOUT volume' 20

# aec reference capture
#amixer -D hw:audiocodec cset name='ADCL Input MIC1 Boost Switch' 1
#amixer -D hw:audiocodec cset name='ADCR Input MIC2 Boost Switch' 1
#amixer -D hw:audiocodec cset name='MIC1 gain volume' 0
#amixer -D hw:audiocodec cset name='MIC2 gain volume' 0

# mic capture, 24dB
#amixer -D hw:sndac10710036 cset name='Channel 1 PGA Gain' 25
#amixer -D hw:sndac10710036 cset name='Channel 2 PGA Gain' 25

# Lancement d'Obico au demarrage apres un delai de 30s (Moonraker doit etre fonctionnel avant)
sleep 30 && /usr/share/moonraker-obico/obico-start.sh

exit 0
`

And with these, it works perfectly on my SonicPad, so I don't see why it doesn't work on yours as manually it's ok for you :-(

**Comment by LeBrunton** [comment]
with your modified obico-start.sh script i get the following error:

/usr/share/moonraker-obico/obico-start2.sh: source: line 5: can't open 'env/bin/activate'

**Comment by fran6p** [comment]
Sorry but as it works for me with what I have written above I don't understand why it won't work for you.
I tried to help as the original writer doesn't seem to respond but the issues on github are not normally where to help users.

I think you missed a part of the installation (python for obico is normally installed separately from the OS in a «virtual» environment), if installed correctly you should have the env/bin directory under /usr/share/moonraker-obico.
:-)

**Comment by fmaranhao** [comment]
> My script obico-start.sh is a little different :
> 
> ```
> #!/bin/sh
> PYTHONPATH=/usr/share/moonraker-obico
> PROG="$PYTHONPATH/env/bin/python3"
> 
> cd $PYTHONPATH
> source env/bin/activate
> $PROG -m moonraker_obico.app -c $PYTHONPATH/moonraker-obico.cfg
> ```
> 
> My rc.local :
> 
> ```
> # Put your custom commands here that should be executed once
> # the system init finished. By default this file does nothing.
> 
> # hpout playback
> #amixer -D hw:audiocodec cset name='Headphone Switch' 1
> #amixer -D hw:audiocodec cset name='Headphone Volume' 3
> #amixer -D hw:audiocodec cset name='HpSpeaker Switch' 1
> 
> # lineout playback
> #amixer -D hw:audiocodec cset name='LINEOUT Output Select' 'DAC_DIFFER'
> #amixer -D hw:audiocodec cset name='LINEOUT Switch' 1
> #amixer -D hw:audiocodec cset name='LINEOUT volume' 20
> 
> # aec reference capture
> #amixer -D hw:audiocodec cset name='ADCL Input MIC1 Boost Switch' 1
> #amixer -D hw:audiocodec cset name='ADCR Input MIC2 Boost Switch' 1
> #amixer -D hw:audiocodec cset name='MIC1 gain volume' 0
> #amixer -D hw:audiocodec cset name='MIC2 gain volume' 0
> 
> # mic capture, 24dB
> #amixer -D hw:sndac10710036 cset name='Channel 1 PGA Gain' 25
> #amixer -D hw:sndac10710036 cset name='Channel 2 PGA Gain' 25
> 
> # Lancement d'Obico au demarrage apres un delai de 30s (Moonraker doit etre fonctionnel avant)
> sleep 30 && /usr/share/moonraker-obico/obico-start.sh
> 
> exit 0
> ```
> 
> And with these, it works perfectly on my SonicPad, so I don't see why it doesn't work on yours as manually it's ok for you :-(

Too bad I didn't come to the comments earlier. I had to figure out all the above by myself! 😜 We should ask the author to update his instructions with your changes above.

**Comment by LeBrunton** [comment]
Solved the issue, it was a typo on my part in the PYTHONPATH in my obico-start.sh
